{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0b348dba_5c3408d5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1045544
      },
      "writtenOn": "2021-01-19T11:26:25Z",
      "side": 1,
      "message": "It\u0027s an unrelated broken internal test. Which one it is shouldn\u0027t matter. It is fixed this morning with b/177374067. Retrying again.",
      "revId": "dcff00c8a82718f319488ce8548dcd192e841405",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}